# Generated by Django 3.0.7 on 2020-06-04 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertype', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_Doctor',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='is_Hospital',
            field=models.BooleanField(default=False),
        ),
    ]
