# Generated by Django 3.0.7 on 2020-06-05 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usertype', '0003_hospital'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hospital',
            name='Phone_Number',
        ),
        migrations.AddField(
            model_name='user',
            name='Phone_Number',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
